#!/usr/bin/env python3
"""Render the Pik deck site to a static PDF, one PNG per slide, and NOTES.md from the slides' speaker notes.

    cd /Users/carl/CODELocalProjects/hyderabaddies/deck
    video/pw/bin/python site/render_pdf.py            # writes Pik_deck.pdf, site/NOTES.md, PNGs under site/_render/

Options: --png-dir DIR (default site/_render), --pdf PATH (default deck/Pik_deck.pdf), --no-notes.
Headless Chromium only (Playwright). Opens index.html?print=1, which stacks every slide in its final build state at 1920x1080.
Exits non-zero if the page logged an error, a slide is not 1920x1080, or a [TBD] is still on a slide (listed, not fatal).
"""
import argparse
import pathlib
import re
import sys

from PIL import Image
from playwright.sync_api import sync_playwright

HERE = pathlib.Path(__file__).resolve().parent
DECK = HERE.parent


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:40]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png-dir", default=str(HERE / "_render"))
    ap.add_argument("--pdf", default=str(DECK / "Pik_deck.pdf"))
    ap.add_argument("--no-notes", action="store_true")
    a = ap.parse_args()
    png_dir = pathlib.Path(a.png_dir)
    png_dir.mkdir(parents=True, exist_ok=True)
    for old in png_dir.glob("*.png"):
        old.unlink()

    errors = []
    with sync_playwright() as p:
        b = p.chromium.launch(headless=True)
        pg = b.new_page(viewport={"width": 1920, "height": 1080}, device_scale_factor=1)
        pg.on("pageerror", lambda e: errors.append("pageerror: " + str(e)))
        pg.on("console", lambda m: errors.append("console." + m.type + ": " + m.text) if m.type == "error" else None)
        pg.goto((HERE / "index.html").as_uri() + "?print=1")
        pg.wait_for_function("window.__deckReady===true", timeout=60000)
        pg.wait_for_timeout(600)
        info = pg.evaluate(
            """() => [...document.querySelectorAll('.slide')].map(s => {
                const r = s.getBoundingClientRect();
                const h1 = s.querySelector('h1') || s.querySelector('.sub');
                return {name: s.dataset.name || s.id, label: (s.querySelector('.prog')||{}).textContent || '',
                        title: h1 ? h1.textContent.trim() : '', w: r.width, h: r.height,
                        tbd: (s.innerText.match(/\\[TBD[^\\]]*\\]/g) || []),
                        steps: [...s.querySelectorAll('.notes p')].map(p => ({n: +p.dataset.step, text: p.textContent.trim()}))}
            })"""
        )
        files = []
        for i, el in enumerate(pg.query_selector_all(".slide")):
            f = png_dir / f"{i + 1:02d}_{slug(info[i]['name'])}.png"
            el.screenshot(path=str(f))
            files.append(f)
        b.close()

    bad = [s for s in info if round(s["w"]) != 1920 or round(s["h"]) != 1080]
    for s in bad:
        errors.append(f"slide {s['name']} is {s['w']}x{s['h']}, not 1920x1080")

    ims = [Image.open(f).convert("RGB") for f in files]
    ims[0].save(a.pdf, save_all=True, append_images=ims[1:], resolution=96.0, quality=95,
                title="Pik, Recruit Innovation Cup 2026, team hyderabaddies")
    size = pathlib.Path(a.pdf).stat().st_size

    if not a.no_notes:
        out = ["# Pik deck, speaker notes and build cues", "",
               "Generated by `site/render_pdf.py` from the `<aside class=\"notes\">` of each slide in `site/index.html`; edit the HTML, not this file.",
               "Keys: Right or Space = next build step, then next slide. Left = back. N = notes drawer. Digits jump to a slide. `?slide=N` opens one. Click = next step.", ""]
        for s in info:
            out.append(f"## {s['label'] or s['name']}: {s['name']}")
            if s["title"]:
                out.append(f"*{s['title']}*")
            out.append("")
            for st in s["steps"]:
                cue = "On arrival" if st["n"] == 0 else f"Keypress {st['n']}"
                out.append(f"- **{cue}.** {st['text']}")
            out.append("")
        (HERE / "NOTES.md").write_text("\n".join(out), encoding="utf-8")

    tbd = [(s["name"], s["tbd"]) for s in info if s["tbd"]]
    print(f"slides: {len(files)}  pdf: {a.pdf}  pages: {len(ims)}  size: {size/1e6:.1f} MB  pngs: {png_dir}")
    for name, t in tbd:
        print(f"[TBD] still on slide {name}: {t}")
    if errors:
        print("PAGE ERRORS (the render is not clean):", file=sys.stderr)
        for e in errors:
            print("  " + e, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
